# This file follows the WordPress CSS standards as closely as possible. For any
# linters that aren't listed in this file, we're accepting the default settings.

# https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/
# Linter documentation: http://git.io/vG7gu
# See also: http://sass-guidelin.es/

linters:

  Comment:
    enabled: false
    # We'll be minifying CSS, which will remove comments.

  DisableLinterReason:
    enabled: true
    # We should document exceptions to the rules.

  IdSelector:
    enabled: false
    # WordPress spits out IDs like it's going out of style (which it is).

  Indentation:
    enabled: true
    character: tab
    width: 1
    # Because the WP standards say so.

  LeadingZero:
    enabled: true
    style: include_zero
    # WordPress standards say this is the cool thing to do.

  PropertySortOrder:
    enabled: false

  PropertySpelling:
    enabled: true
    extra_properties: []
    # This is enabled by default. We're leaving a place to add extra properties.

  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false
    # The WP standards say that single line rule sets are verboten.

  StringQuotes:
    enabled: true
    style: double_quotes
    # In WP land, all the cool kids use double quotes.

  UrlFormat:
    enabled: false
    # We'll need to use URLs with domains in order to load our fonts.

  UrlQuotes:
    enabled: false
    # WP standards say that quotes in URLs are for wimps.
